In [1]:
import pandas as pd
import numpy as np

In [51]:
path = 'dataset\SPAS-Dataset-BD.csv'
data = pd.read_csv(path)
data

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\urja tendolkar\AppData\Local\Temp\ipykernel_1884\2306899975.py:1: SyntaxWarning: invalid escape sequence '\S'
  path = 'dataset\SPAS-Dataset-BD.csv'

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,Production,Max Temp,Min Temp,Max Relative Humidity,Min Relative Humidity
0,177321,0.8510272331,Bagerhat,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,150905,40,12.0,60,85
1,25646,1.175777899,Bandarban,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,30154,40,12.0,60,85
2,231401,0.7705887183,Barguna,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,178315,40,12.0,60,85
3,302665,0.7571043893,Barishal,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,229149,40,12.0,60,85
4,388575,1.100652384,Bhola,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,427686,40,12.0,60,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4603,256,2.1953125,Sirajganj,Kharif 1,25.0,70.0,Wood Apple,May,June to August,August to September,562,30,20.0,60,80
4604,50,1.38,Sunamganj,Kharif 1,25.0,70.0,Wood Apple,May,June to August,August to September,69,30,20.0,60,80
4605,95,1.242105263,Sylhet,Kharif 1,25.0,70.0,Wood Apple,May,June to August,August to September,118,30,20.0,60,80
4606,497,1.348088531,Tangail,Kharif 1,25.0,70.0,Wood Apple,May,June to August,August to September,670,30,20.0,60,80
4607,49,1.469387755,Thakurgaon,Kharif 1,25.0,70.0,Wood Apple,May,June to August,August to September,72,30,20.0,60,80

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4608 entries, 0 to 4607
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Area                   4608 non-null   int64
 1   AP Ratio               4608 non-null   object
 2   District               4608 non-null   object
 3   Season                 4607 non-null   object
 4   Avg Temp               4608 non-null   float64
 5   Avg Humidity           4608 non-null   float64
 6   Crop Name              4608 non-null   object
 7   Transplant             4608 non-null   object
 8   Growth                 4608 non-null   object
 9   Harvest                4608 non-null   object
 10  Production             4608 non-null   int64
 11  Max Temp               4608 non-null   int64
 12  Min Temp               4608 non-null   float64
 13  Max Relative Humidity  4608 non-null   int64
 14  Min Relative Humidity  4608 non-null   int64
dtypes: float64(3), int64(5), object(7)
memory usage: 540.1+ KB

In [53]:
data.describe()

,Area,Avg Temp,Avg Humidity,Production,Max Temp,Min Temp,Max Relative Humidity,Min Relative Humidity
count,4608.000000,4608.000000,4608.000000,4.608000e+03,4608.000000,4608.000000,4608.000000,4608.000000
mean,8084.877604,23.878472,71.597222,1.443418e+04,30.736111,17.020833,61.513889,81.680556
std,42154.348588,4.721549,11.245552,6.562959e+04,5.956486,5.407911,12.785919,11.340477
min,0.000000,11.500000,35.000000,0.000000e+00,15.000000,5.000000,20.000000,45.000000
25%,61.000000,20.000000,67.500000,1.197500e+02,25.000000,14.750000,58.000000,78.750000
50%,280.000000,25.000000,72.500000,7.260000e+02,30.000000,18.000000,60.000000,85.000000
75%,821.250000,27.500000,80.000000,2.881000e+03,35.000000,20.000000,70.000000,90.000000
max,663734.000000,34.500000,90.000000,1.077242e+06,47.000000,27.000000,85.000000,100.000000

### This dataset has no missing values, so no further pre processing for missing needed

In [54]:
reduced_df = data.drop(
    ['Production'], axis = 1)

In [55]:
reduced_df.head()

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,Max Temp,Min Temp,Max Relative Humidity,Min Relative Humidity
0,177321,0.8510272331,Bagerhat,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,40,12.0,60,85
1,25646,1.175777899,Bandarban,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,40,12.0,60,85
2,231401,0.7705887183,Barguna,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,40,12.0,60,85
3,302665,0.7571043893,Barishal,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,40,12.0,60,85
4,388575,1.100652384,Bhola,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,40,12.0,60,85

In [56]:
reduced_df.Transplant.value_counts()

Transplant
April        838
Oct          768
Sep          704
March        454
June         453
Aug          384
Nov          256
July         133
May          133
Feb          128
Jan          128
Dec          128
February      71
September      5
August         5
January        5
November       5
October        5
December       5
Name: count, dtype: int64

In [57]:
month_dict = {'January':'Jan', 'February':'Feb', 'March':'Mar', 'April':'Apr', 'May':'May', 'June':'Jun', 'July':'Jul', 'August':'Aug', 'September':'Sep', 'October':'Oct', 'November':'Nov', 'December':'Dec'}
for key in reduced_df.Transplant.unique():
    if key in month_dict:
        reduced_df.Transplant.replace(key, month_dict[key], inplace=True)

C:\Users\urja tendolkar\AppData\Local\Temp\ipykernel_1884\3184104418.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reduced_df.Transplant.replace(key, month_dict[key], inplace=True)

In [58]:
reduced_df.Transplant.value_counts()

Transplant
Apr    838
Oct    773
Sep    709
Mar    454
Jun    453
Aug    389
Nov    261
Feb    199
Jan    133
Jul    133
Dec    133
May    133
Name: count, dtype: int64

In [59]:
reduced_df.Growth.value_counts()

Growth
No need to do     640
Nov to March      384
Oct to Nov        320
June to August    320
Nov to Feb        256
April to Aug      256
Sep to Jan        192
Sep to Oct        192
Nov to Jan        128
July to August    128
May to June       128
Jan  to  March    128
Aug to Jan        128
Dec to March      128
Oct to Dec        128
Jan to Jan        128
Dec to Feb         64
April to July      64
Oct to Jan         64
July to Nov        64
April to july      64
July to  Oct       64
May to July        64
March to July      64
April to May       64
Nov  to  Feb       64
March to May       64
May to Sep         64
Sep to May         64
Dec to Jan         64
Nov to Aug         64
March to April     64
Name: count, dtype: int64

In [60]:
for key in reduced_df.Growth.unique():
    start, end = key.split('to')
    if start.strip() in month_dict: 
        start = month_dict[start.strip()]
    if end.strip() in month_dict:
        end = month_dict[end.strip()]

    new_key = start + ' to ' + end
    reduced_df.Growth.replace(key, new_key, inplace=True)

reduced_df.Growth.value_counts()

C:\Users\urja tendolkar\AppData\Local\Temp\ipykernel_1884\2513808574.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reduced_df.Growth.replace(key, new_key, inplace=True)

Growth
No need  to  do    640
Nov  to Mar        384
Nov   to   Feb     320
Oct  to  Nov       320
Jun to Aug         320
Apr to  Aug        256
Sep  to  Oct       192
Sep  to  Jan       192
Nov  to  Jan       128
Aug  to  Jan       128
Jan   to Mar       128
Dec  to Mar        128
Jul to Aug         128
Oct  to  Dec       128
Jan  to  Jan       128
May to Jun         128
Apr to Jul          64
Apr to  july        64
Jul to  Nov         64
Jul to   Oct        64
Oct  to  Jan        64
Dec  to  Feb        64
May to Jul          64
Apr to May          64
Mar to Jul          64
Mar to May          64
May to  Sep         64
Sep  to May         64
Dec  to  Jan        64
Nov  to  Aug        64
Mar to Apr          64
Name: count, dtype: int64

In [61]:
reduced_df.Harvest.value_counts()

Harvest
Feb                    384
August to September    320
Nov to Feb             320
March to April         320
Jan to March           256
April                  256
Sep                    192
Nov                    192
Feb to April           192
April to June          128
Throuout The year      128
March                  128
Aug to Sep             128
June to Aug            128
Feb to March           128
May                    128
June  to September     128
Jan                    128
Nov to Dec              64
July to Oct             64
March to jun            64
Nov to April            64
December to April       64
Aug                     64
February to March       64
May to June             64
July to Sep             64
Sep to Oct              64
June to Sep             64
June to July            64
Sep to Feb              64
Dec to Feb              64
April to May            64
February to May         64
Name: count, dtype: int64

In [62]:
for key in reduced_df.Harvest.unique():
    if 'to' not in key:
        if key.strip() in month_dict:
            reduced_df.Harvest.replace(key, month_dict[key.strip()], inplace=True)
        continue
    start, end = key.split('to')
    if start.strip() in month_dict: 
        start = month_dict[start.strip()]
    if end.strip() in month_dict:
        end = month_dict[end.strip()]

    new_key = start + ' to ' + end
    reduced_df.Harvest.replace(key, new_key, inplace=True)

reduced_df.Harvest.value_counts()

C:\Users\urja tendolkar\AppData\Local\Temp\ipykernel_1884\2154842035.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reduced_df.Harvest.replace(key, new_key, inplace=True)
C:\Users\urja tendolkar\AppData\Local\Temp\ipykernel_1884\2154842035.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reduced_df.Harvest.replace(key, month_dict[key.strip()], inplace=True)

Harvest
Aug  to  Sep         448
Feb                  384
Mar to Apr           320
Nov  to  Feb         320
Apr                  256
Jan  to Mar          256
Sep                  192
Nov                  192
Feb  to Apr          192
May                  128
Jun to Sep           128
Mar                  128
Apr to Jun           128
Throuout The year    128
Feb  to Mar          128
Jun to  Aug          128
Jan                  128
Nov  to  Dec          64
Jul to  Oct           64
Mar to  jun           64
Dec to Apr            64
Nov  to Apr           64
Aug                   64
Feb to Mar            64
May to Jun            64
Jul to  Sep           64
Sep  to  Oct          64
Jun to  Sep           64
Jun to Jul            64
Sep  to  Feb          64
Dec  to  Feb          64
Apr to May            64
Feb to May            64
Name: count, dtype: int64

In [63]:
reduced_df.head()

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,Max Temp,Min Temp,Max Relative Humidity,Min Relative Humidity
0,177321,0.8510272331,Bagerhat,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
1,25646,1.175777899,Bandarban,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
2,231401,0.7705887183,Barguna,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
3,302665,0.7571043893,Barishal,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
4,388575,1.100652384,Bhola,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85

In [64]:
reduced_df['AP Ratio'].value_counts()

AP Ratio
#DIV/0!         416
2                19
1                19
0.5              16
0                13
               ...
1.202152897       1
1.126656938       1
1.185907927       1
0.7519377261      1
1.469387755       1
Name: count, Length: 3893, dtype: int64

In [65]:
data.Production.value_counts()

Production
0         422
2          26
1          21
4          19
9          19
         ...
201325      1
94005       1
435070      1
158565      1
70243       1
Name: count, Length: 2571, dtype: int64

In [66]:
reduced_df["AP Ratio"] = pd.to_numeric(reduced_df["AP Ratio"], errors="coerce")
reduced_df["AP Ratio"].value_counts()

AP Ratio
1.000000    19
2.000000    19
0.500000    16
0.000000    13
3.000000    12
            ..
1.040176     1
1.202153     1
1.126657     1
1.185908     1
1.295082     1
Name: count, Length: 3892, dtype: int64

In [67]:
reduced_df['AP Ratio'].isna().sum()

np.int64(416)

In [68]:
reduced_df.dropna(inplace=True)

In [69]:
reduced_df

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,Max Temp,Min Temp,Max Relative Humidity,Min Relative Humidity
0,177321,0.851027,Bagerhat,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
1,25646,1.175778,Bandarban,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
2,231401,0.770589,Barguna,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
3,302665,0.757104,Barishal,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
4,388575,1.100652,Bhola,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4603,256,2.195312,Sirajganj,Kharif 1,25.0,70.0,Wood Apple,May,Jun to Aug,Aug to Sep,30,20.0,60,80
4604,50,1.380000,Sunamganj,Kharif 1,25.0,70.0,Wood Apple,May,Jun to Aug,Aug to Sep,30,20.0,60,80
4605,95,1.242105,Sylhet,Kharif 1,25.0,70.0,Wood Apple,May,Jun to Aug,Aug to Sep,30,20.0,60,80
4606,497,1.348089,Tangail,Kharif 1,25.0,70.0,Wood Apple,May,Jun to Aug,Aug to Sep,30,20.0,60,80
4607,49,1.469388,Thakurgaon,Kharif 1,25.0,70.0,Wood Apple,May,Jun to Aug,Aug to Sep,30,20.0,60,80

In [70]:
reduced_df.Season.value_counts()

Season
Kharif 2    1578
Kharif 1    1421
Rabi        1192
Name: count, dtype: int64

In [71]:
reduced_df.rename(columns={'Max Relative Humidity': 'min relative humidity', 'Min Relative Humidity': 'max relative humidity'}, inplace=True)
reduced_df.head()

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,Max Temp,Min Temp,min relative humidity,max relative humidity
0,177321,0.851027,Bagerhat,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
1,25646,1.175778,Bandarban,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
2,231401,0.770589,Barguna,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
3,302665,0.757104,Barishal,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85
4,388575,1.100652,Bhola,Kharif 2,26.0,72.5,Aman,Jun,Jul to Oct,Nov to Dec,40,12.0,60,85

In [72]:
reduced_df.Area.value_counts()

Area
4         30
2         24
11        21
10        21
5         21
          ..
10947      1
163129     1
191856     1
645472     1
18702      1
Name: count, Length: 1771, dtype: int64